### ISSUE TITLE
Create spawn mechanic for sprites

### ISSUE THREAD

**Issue by orphuz** [orphuz/space-wars#10]
### **Create spawn and despawn mechanic for sprites**

(Non) existence of sprites (enemies and missiles) is currently managed by placing them inside or outside the visibile canvas. Instead every existing sprite should be represented by a class.

**SubTasks:**
- [x] Spawn new enemies/missles by creating new sprite objects
- [x] Despawn enemies/missiles by deconstructing sprite objects.
- [x] Keep track of exisitng enemies/missiles (sprite objects)
- [x] Prevent enemies from spawning in or near the current player position

**Comment by orphuz** [comment]
fixed on dev with c1a74c57437208d3366f8f32ea3f340d61e476c7

**Comment by orphuz** [comment]
Fixed on master with #35
