### ISSUE TITLE
Make game config externally editable

### ISSUE THREAD

**Issue by orphuz** [orphuz/space-wars#11]
**### Make game config externally editable** 
Mainly for education purose: Create an external config file where the game config is stored and can be modified.

**SubTasks**
- [x] Decide with file format shall be used
- [x] Define external config file
- [x] Check if config file exists
- [x] If yes, read external config file at the start of the game and use it's variables
- [x] If not, writ defaul verison of external config file and use default variables

**Hint:** Use python module [configparser](https://docs.python.org/3/library/configparser.html)

**Comment by orphuz** [comment]
fixed on dev with 990196f767fac803fdd6ac3490a9aa5b24733073

**Comment by orphuz** [comment]
Implemented with: 990196f767fac803fdd6ac3490a9aa5b24733073
