### ISSUE TITLE
Optimize boundary detection

### ISSUE THREAD

**Issue by orphuz** [orphuz/space-wars#6]
Currently boundary detection is based on the coordinates of the sprites without considering theier body size (e.g. radius or covered area). 

This should could be changed by difining a radius covered by each sprite which can be taken into account in the collision detection algorythm..

**SubTasks:**
- [x] Define sprite sizes
- [x] Introduce sprite radius based on sprite size
- [x] Include sprite radius in collision detcting algorythms

**Comment by orphuz** [comment]
implemented in branch **dev** with 87e1a548e29eb3e7325a9474f2fffe760da09463
